[build-system]
requires = ["setuptools>=76.1.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version", "dependencies", "optional-dependencies"]
name = "ocs-csb"
authors = [
    { name="Anthony Klemm", email="anthony.r.klemm@noaa.gov" },
    { name="Brian Calder", email="brc@ccom.unh.edu" },
    { name="Brian Miles", email="bmiles@ccom.unh.edu" },
]
description = "NOAA Office of Coast Survey Crowdsource Bathymetry Processing Code"
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/anthonyklemm/csb_processing_pipeline"
"Bug Tracker" = "https://github.com/anthonyklemm/csb_processing_pipeline/issues"

[project.scripts]
processing = "ocscsb.gui:cli"
ocscsb = "ocscsb.command:cli"
leaderboard = "dashboard.leaderboard:cli"
dashboard = "dashboard.dashboard:cli"

[tool.setuptools.dynamic]
version = {attr = "ocscsb.__version__"}
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {test = {file = ["requirements-test.txt"]}, dashboard = {file = ["requirements-dash.txt"]}}

[tool.setuptools]
include-package-data = true
