# -*- coding: utf-8 -*-
"""
Created on Thu Apr  4 15:08:15 2024

@author: Anthony.R.Klemm
"""
# After code execution, open up web browser and navigate to this URL:
    # http://127.0.0.1:8050/

import sys
from pathlib import Path
import dash
from dash import dcc  
from dash import html
import plotly.express as px
import pandas as pd
import click

from ocscsb import __version__ as version

# Initialize the Dash app
app = dash.Dash(__name__)

@click.command()
@click.version_option(version=version)
@click.argument('offsets', type=click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path))
@click.argument('leaders', type=click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path))
@click.option('--port', type=int, default=8050, help='Set server port to listen on.')
def cli(offsets: Path, leaders: Path, port: int) -> None:
    '''Run a Dash based dashboard for leaders/accuracies

    This command starts a local Dash server showing plots of the leading providers of
    data in the local environment (as generated by the "leaderboard" command), and their
    accuracies.  OFFSETS specifies the CSV file with accuracy information (typically the processed CSB data
    after correction); LEADERS specifies the CSV file with the leaderboard information.
    '''

    offsets_df = pd.read_csv(offsets)
    offsets_df = offsets_df.query("platform_name != 'Anonymous'")
    leader_df = pd.read_csv(leaders)
    leader_df = leader_df.query("`Platform Name` != 'Anonymous'")

    # Plot objects for the dashboard: providers and miles given, and accuracies (comparison to reference)
    leader_bar = px.bar(leader_df, x="Platform Name", y="Total Distance (nautical miles)",
                        title="CSB Contributors NE Leaderboard - mileage")
    leader_bar.update_layout(height=800)
    accuracy_score = px.bar(offsets_df, x='platform_name', y='accuracy_score',
                            title="Accuracy score (inverse of std_dev of comparison to reference bathy)")
    accuracy_score.update_layout(height=800)

    # Define the layout of the app
    app.layout = html.Div(children=[
        html.Div(children='''
            Dash: A web application framework for Python.
        '''),
        dcc.Graph(
            id='leaderboard-contributors',
            figure=leader_bar
        ),
        dcc.Graph(
            id='accuracy-score-graph',
            figure=accuracy_score
        )
    ])
    app.run_server(debug=True, port=port)

if getattr(sys, 'frozen', False):
    cli(sys.argv[1:])
